name: flutter_widget
description: Flutter Widget
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_core:
    path: ../flutter_core

  flutter_svg: ^2.0.7
  flutter_bloc: ^8.1.2
  shimmer: ^3.0.0
  flutter_svg_provider: ^1.0.6
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.4
  flutter_gen_runner: ^5.3.1

flutter:
#  assets:
    # color: Color image not changed by theme
    # dark: dark theme image, name must same as light image
    # light: light theme image, name must same as dark image
    # solid: image using tint color